# Generated by Django 4.2.7 on 2023-12-06 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_alter_order_order_status_alter_order_page_number"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="printBindingType",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="printBindingTypess",
                to="orders.printbindingtypes",
            ),
        ),
        migrations.DeleteModel(
            name="PrintBindingTypes",
        ),
    ]
