# Generated by Django 4.2.7 on 2023-12-11 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="printBindingType",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="printBindingTypess",
                to="orders.printbindingtypes",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="printColor",
            field=models.IntegerField(
                choices=[(1, "Oq qora"), (2, "Rangli")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="printSize",
            field=models.IntegerField(choices=[(1, "A5"), (2, "A4")], default=1),
        ),
        migrations.DeleteModel(
            name="PrintBindingTypes",
        ),
    ]
