# Generated by Django 4.2.7 on 2023-12-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_printbindingtype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="printColor",
            field=models.IntegerField(
                choices=[(1, "Oq qora"), (2, "Rangli")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="printSize",
            field=models.IntegerField(choices=[(1, "A5"), (2, "A4")], default=1),
        ),
    ]
