# Generated by Django 4.2.7 on 2024-01-03 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Mahsulot", "verbose_name_plural": "Mahsulotlar"},
        ),
    ]
