# Generated by Django 4.2.7 on 2024-01-10 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Buyurtma", "verbose_name_plural": "Buyurtmalar"},
        ),
        migrations.AlterField(
            model_name="order",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20, verbose_name="Balans"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="cash_type",
            field=models.IntegerField(
                choices=[(1, "Naqt"), (2, "Karta orqali"), (3, "To'lanmadi")],
                default=3,
                verbose_name="Pul turi",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Yaratilgan vaqt"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.IntegerField(
                choices=[(1, "O'zim olib ketaman"), (2, "Kuryerlik xizmati")],
                default=1,
                verbose_name="Yetqazib berish turi",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="file",
            field=models.FileField(upload_to="uploads/%Y/%m/%d/", verbose_name="Fayl"),
        ),
        migrations.AlterField(
            model_name="order",
            name="file_status",
            field=models.BooleanField(default=False, verbose_name="Fayl statusi"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.IntegerField(
                choices=[
                    (1, "Yaratilish"),
                    (2, "Yangi Buyurtma"),
                    (3, "Faol"),
                    (4, "Bekor qilingan"),
                    (5, "Yetqazib berilgan"),
                ],
                default=1,
                verbose_name="Buyurtma statusi",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="page_number",
            field=models.IntegerField(default=0, verbose_name="Sahifa soni"),
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=20, verbose_name="Narx"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="printColor",
            field=models.IntegerField(
                choices=[(1, "Oq qora"), (2, "Rangli")], default=1, verbose_name="Rang"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="printSize",
            field=models.IntegerField(
                choices=[(1, "A5"), (2, "A4")], default=2, verbose_name="Hajmi"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tg_pk",
            field=models.CharField(
                default=0, max_length=150, verbose_name="Telegram id"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_credit",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20, verbose_name="Umumiy kredit"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_debit",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20, verbose_name="Umumiy debit"
            ),
        ),
    ]
