# Generated by Django 4.2.7 on 2023-12-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_cash_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name="order",
            name="residual_value",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
