# Generated by Django 4.2.7 on 2023-12-04 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintBindingTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=150, verbose_name="name"),
                ),
                ("photo", models.FileField(upload_to="binding/%Y/%m/%d/")),
            ],
            options={
                "verbose_name": "Тип переплета печати",
                "verbose_name_plural": "Типы переплета печати",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="printBindingType",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="printBindingTypes",
                to="orders.printbindingtypes",
            ),
        ),
    ]
