# Generated by Django 4.2.4 on 2024-01-19 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_clientaddress_latitude_and_more'),
        ('orders', '0003_alter_order_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_order', to='accounts.company'),
        ),
    ]
