# Generated by Django 4.2.7 on 2023-12-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_paid_amount_order_residual_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="paid_amount",
        ),
        migrations.AddField(
            model_name="order",
            name="total_credit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_debit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="residual_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
