# Generated by Django 4.2.7 on 2023-12-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_remove_order_paid_amount_order_total_credit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="residual_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_credit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_debit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
