# Generated by Django 4.2.7 on 2023-12-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_printbindingtypes_alter_order_printbindingtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printbindingtypes",
            name="name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Nomi"),
        ),
    ]
