# Generated by Django 4.2.7 on 2023-12-05 04:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_printbindingtypes_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="printbindingtypes",
            options={
                "verbose_name": "Bindinr type",
                "verbose_name_plural": "Biding types",
            },
        ),
    ]
