# Generated by Django 4.2.7 on 2024-01-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_alter_order_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="residual_value",
        ),
        migrations.AddField(
            model_name="order",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
