# Generated by Django 4.2.7 on 2023-12-05 04:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_alter_printbindingtypes_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="printbindingtypes",
            options={
                "verbose_name": "Binding type",
                "verbose_name_plural": "Biding types",
            },
        ),
    ]
