# Generated by Django 4.2.7 on 2023-12-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_alter_printbindingtypes_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Buyurtma raqami"
            ),
        ),
    ]
