# Generated by Django 4.2.7 on 2024-01-06 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_clientaddress_company_location"),
        ("orders", "0007_remove_order_residual_value_order_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="location",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.clientaddress",
            ),
        ),
        migrations.DeleteModel(
            name="ClientAddress",
        ),
    ]
