# Generated by Django 4.2.7 on 2023-12-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_alter_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.IntegerField(
                choices=[
                    (1, "В создании"),
                    (2, "В подтверждении"),
                    (3, "Активный"),
                    (4, "Отменено"),
                    (5, "Доставлен"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="page_number",
            field=models.IntegerField(default=0),
        ),
    ]
