# Generated by Django 4.2.7 on 2023-12-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_alter_order_order_status_alter_order_page_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="file_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="tg_pk",
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.IntegerField(
                choices=[
                    (1, "Yangi"),
                    (2, "Buyurtma berilgan"),
                    (3, "Faol"),
                    (4, "Bekor qilingan"),
                    (5, "Yetqazib berilgan"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="printColor",
            field=models.IntegerField(
                choices=[(1, "Oq qora"), (2, "Rangli")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="printSize",
            field=models.IntegerField(choices=[(1, "A5"), (2, "A4")], default=2),
        ),
    ]
