# Generated by Django 4.2.7 on 2023-12-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_order_file_status_order_tg_pk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cash_type",
            field=models.IntegerField(
                choices=[(1, "Naqt"), (2, "Karta orqali")], default=1
            ),
        ),
    ]
