# Generated by Django 4.2.7 on 2024-01-10 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientaddress",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="clientaddress",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="clientaddress",
            name="name",
            field=models.CharField(
                default="some place", max_length=255, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20, verbose_name="Balans"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(blank=True, max_length=55, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="company",
            name="total_credit",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20, verbose_name="Umumiy kredit"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="total_debit",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20, verbose_name="Umumiy deit"
            ),
        ),
        migrations.AlterField(
            model_name="moneysaver",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20, verbose_name="Balans"
            ),
        ),
        migrations.AlterField(
            model_name="moneysaver",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Yaratilgan vaqt"
            ),
        ),
        migrations.AlterField(
            model_name="moneysaver",
            name="deleted_status",
            field=models.BooleanField(
                default=False, verbose_name="O'chirilganlik statusi"
            ),
        ),
        migrations.AlterField(
            model_name="moneysaver",
            name="total_credit",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20, verbose_name="Umumiy kredit"
            ),
        ),
        migrations.AlterField(
            model_name="moneysaver",
            name="total_debit",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20, verbose_name="Umumiy debit"
            ),
        ),
        migrations.AlterField(
            model_name="moneysaver",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="O'zgartirilgan vaqt"
            ),
        ),
    ]
