# Generated by Django 4.2.4 on 2024-01-23 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_clientaddress_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_address', to='accounts.clientaddress'),
        ),
    ]
