# Generated by Django 4.2.7 on 2023-12-22 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_company_balance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "verbose_name": "Kompaniya",
                "verbose_name_plural": "Kompaniyalar",
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Foydanuvchi",
                "verbose_name_plural": "Foydalanuvchilar",
            },
        ),
    ]
