# Generated by Django 4.2.4 on 2024-01-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_company_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientaddress',
            unique_together={('name', 'latitude', 'longitude')},
        ),
    ]
