# Generated by Django 4.2.7 on 2023-12-22 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_company_options_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userrole",
            options={
                "verbose_name": "Foydaluvchilar turi",
                "verbose_name_plural": "Foydaluvchilar turlari",
            },
        ),
    ]
