# Generated by Django 4.2.7 on 2023-12-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_userrole_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoneySaver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reester_number",
                    models.CharField(
                        blank=True, max_length=55, verbose_name="Reyester"
                    ),
                ),
                (
                    "cashType",
                    models.IntegerField(
                        choices=[(1, "Naqt"), (2, "Bank"), (3, "Mahsulot")],
                        default=1,
                        verbose_name="Pul turi",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Pul saqlash turi",
                "verbose_name_plural": "Pul saqlash turlari",
            },
        ),
    ]
