# Generated by Django 4.2.7 on 2023-12-22 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_moneysaver"),
    ]

    operations = [
        migrations.AddField(
            model_name="moneysaver",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_moneySaver",
                to="accounts.company",
            ),
        ),
    ]
