# Generated by Django 4.2.7 on 2023-12-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_company_balance_alter_moneysaver_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="total_credit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="total_debit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
