# Generated by Django 4.2.7 on 2023-12-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_company_total_credit_company_total_debit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="company",
            name="total_credit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="company",
            name="total_debit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
