# Generated by Django 4.2.7 on 2024-01-03 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_company_balance_alter_company_total_credit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moneysaver",
            name="company",
        ),
        migrations.AddField(
            model_name="company",
            name="money_saver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_moneySaver",
                to="accounts.moneysaver",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.TextField(blank=True, max_length=100, verbose_name="Manzil"),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(
                blank=True, max_length=100, null=True, verbose_name="Pochta"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                blank=True, max_length=55, verbose_name="Nomlanishi"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Telefon"
            ),
        ),
        migrations.AlterField(
            model_name="moneysaver",
            name="cashType",
            field=models.IntegerField(
                choices=[(1, "Naqt"), (2, "Bank")], default=1, verbose_name="Pul turi"
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="code",
            field=models.CharField(max_length=55, verbose_name="Kod"),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="name",
            field=models.CharField(
                blank=True, max_length=55, verbose_name="Nomlanishi"
            ),
        ),
    ]
