# Generated by Django 4.2.7 on 2024-01-03 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_remove_moneysaver_company_company_money_saver_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="money_saver",
        ),
        migrations.AddField(
            model_name="moneysaver",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_moneySaver",
                to="accounts.company",
            ),
        ),
    ]
