# Generated by Django 4.2.7 on 2024-01-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_remove_company_money_saver_moneysaver_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="moneysaver",
            name="total_credit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="moneysaver",
            name="total_debit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
