# Generated by Django 4.2.7 on 2024-01-04 05:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_moneysaver_total_credit_moneysaver_total_debit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moneysaver",
            name="id",
        ),
        migrations.AddField(
            model_name="moneysaver",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
