# Generated by Django 4.2.7 on 2024-01-06 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_clientaddress_company_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="location",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.clientaddress",
            ),
        ),
    ]
