# Generated by Django 4.2.7 on 2024-01-06 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_alter_company_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="location",
        ),
        migrations.AddField(
            model_name="company",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
