# Generated by Django 4.2.7 on 2024-01-06 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_remove_company_location_company_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="location",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_address",
                to="accounts.clientaddress",
            ),
        ),
    ]
