# Generated by Django 4.2.7 on 2024-01-06 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_company_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="uuid",
        ),
        migrations.AlterField(
            model_name="company",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
