# Generated by Django 4.2.7 on 2024-01-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_alter_company_id_alter_customuser_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moneysaver",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
