# Generated by Django 4.2.7 on 2024-01-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0025_moneysaver_created_at_moneysaver_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moneysaver",
            name="deleted_status",
            field=models.BooleanField(default=False),
        ),
    ]
