# Generated by Django 4.2.7 on 2024-01-10 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20, verbose_name="Balans"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="company_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=20,
                verbose_name="Korxona balansi",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Yaratilgan vaqt"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="deleted_status",
            field=models.BooleanField(
                default=False, verbose_name="O'chirilganlik status"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="O'zgartirilgan vaqt"
            ),
        ),
    ]
