# Generated by Django 4.2.7 on 2023-12-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_remove_transaction_product_transaction_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="company_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
