# Generated by Django 4.2.7 on 2023-12-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0003_transaction_company_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_order",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="To'lov raqami"
            ),
        ),
    ]
