# Generated by Django 4.2.7 on 2023-12-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0004_transaction_payment_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="company_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
