# Generated by Django 4.2.7 on 2023-12-22 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_company_balance"),
        ("transactions", "0005_alter_transaction_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_transaction",
                to="accounts.company",
            ),
        ),
    ]
