# Generated by Django 4.2.7 on 2023-12-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0006_transaction_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="company_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
