# Generated by Django 4.2.7 on 2024-01-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0007_alter_transaction_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="cash_type",
            field=models.IntegerField(
                choices=[(1, "Naqt"), (2, "Bank")], default=1, verbose_name="Pul turi"
            ),
        ),
    ]
