# Generated by Django 4.2.7 on 2024-01-03 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_remove_company_money_saver_moneysaver_company"),
        ("transactions", "0008_alter_transaction_cash_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="cash_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moneySaver_transaction",
                to="accounts.moneysaver",
            ),
        ),
    ]
