# Generated by Django 4.2.7 on 2024-01-04 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_remove_moneysaver_id_moneysaver_uuid"),
        ("transactions", "0010_alter_transaction_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="cash_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moneySaver_transaction",
                to="accounts.moneysaver",
            ),
        ),
    ]
