# Generated by Django 4.2.7 on 2023-12-01 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_remove_client_photo"),
        ("tg", "0002_remove_chat_theme_chat_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="subscribers",
            field=models.ManyToManyField(blank=True, to="clients.client"),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clients.client"
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.client",
            ),
        ),
    ]
