# Generated by Django 4.2.7 on 2023-12-27 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tg", "0002_remove_message_chat_delete_chat_delete_theme"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
