# Generated by Django 4.2.7 on 2024-01-02 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tg", "0003_delete_message"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TelegramUser",
        ),
    ]
