# Generated by Django 4.2.7 on 2024-01-08 11:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("userId", models.CharField(blank=True, max_length=13, null=True)),
                ("phone", models.CharField(blank=True, max_length=13, null=True)),
                ("username", models.CharField(max_length=150, verbose_name="username")),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_status", models.BooleanField(default=False)),
                (
                    "total_debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
    ]
