# Generated by Django 4.2.7 on 2024-01-10 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Mijoz", "verbose_name_plural": "Mijozlar"},
        ),
        migrations.AlterField(
            model_name="client",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20, verbose_name="Balans"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="client",
            name="deleted_status",
            field=models.BooleanField(
                default=False, verbose_name="O'chirilganlik statusi"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Ism"),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Familiya"),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(
                blank=True, max_length=13, null=True, verbose_name="Telefon"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="total_credit",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20, verbose_name="Umumiy kredit"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="total_debit",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20, verbose_name="Umumiy debit"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="O'zgartirilgan vaqt"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="userId",
            field=models.CharField(
                blank=True, max_length=13, null=True, verbose_name="Chat id"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="username",
            field=models.CharField(max_length=150, verbose_name="Username"),
        ),
    ]
