# Generated by Django 4.2.7 on 2023-12-04 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_remove_client_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Client", "verbose_name_plural": "Clients"},
        ),
    ]
