# Generated by Django 4.2.7 on 2023-12-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0003_client_residual_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="order_amount",
        ),
        migrations.AlterField(
            model_name="client",
            name="residual_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="client",
            name="total_credit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="client",
            name="total_debit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
